'use strict';
const C=window.SignalDealCore;
const SUPABASE_URL='https://eazukvtjxeirbitukueb.supabase.co';
const KEY='sb_publishable_OIOSgs39cGT6s34eVuexIA_5bZGmZVj';
const CHECKOUT={essential:'https://buy.stripe.com/dRm3cx1GE1WK6v30r06Zy00',pro:'https://buy.stripe.com/00w28tbhe58W3iRgpY6Zy01',agency:'https://buy.stripe.com/6oU28tcli44SaLjgpY6Zy02'};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DIAG=window.SignalDealDiagnostics={apiRequests:0,startedAt:Date.now(),automaticNetwork:false,serviceWorker:false,autoPolling:false};
let session=null,currentPlan='free',rows=[],pipe=[];
const SIM=[
{id:'a1',company:'Agence d’assurance locale',sector:'Assurance / courtage',naf:'66.22Z',city:'Issoire',distance_km:0.8,relation:'prospect',score:94,why:'Agence recevant du public : supports commerciaux et vitrophanie à qualifier.'},
{id:'m1',company:'Cabinet médical local',sector:'Santé / cabinet médical',naf:'86.21Z',city:'Issoire',distance_km:1.1,relation:'prospect',score:88,why:'Besoins possibles en signalétique, papeterie et affichage professionnel.'},
{id:'b1',company:'Magasin bio local',sector:'Commerce de détail',naf:'47.11D',city:'Issoire',distance_km:1.3,relation:'prospect',score:91,why:'Commerce physique avec renouvellement fréquent de communication magasin.'},
{id:'bo1',company:'Boulangerie locale A',sector:'Boulangerie / pâtisserie',naf:'10.71C',city:'Issoire',distance_km:1.6,relation:'prospect',score:89,why:'Affichage prix, menus, étiquettes et campagnes saisonnières possibles.'},
{id:'bo2',company:'Boulangerie locale B',sector:'Boulangerie / pâtisserie',naf:'10.71C',city:'Issoire',distance_km:2.2,relation:'prospect',score:86,why:'Supports de vitrine et communication locale à qualifier.'},
{id:'i1',company:'Autre imprimerie locale',sector:'Imprimerie / production graphique',naf:'18.12Z',city:'Issoire',distance_km:2.6,relation:'competitor',score:0,why:'Activité proche : classée comme concurrent local.'}
];
function saved(){try{return JSON.parse(localStorage.getItem('sdLiteSession')||'null')}catch{return null}}
function save(s){session=s;try{localStorage.setItem('sdLiteSession',JSON.stringify(s))}catch{};updateSessionUi()}
function clear(){session=null;currentPlan='free';try{localStorage.removeItem('sdLiteSession')}catch{};updateSessionUi();$('planLabel').textContent='Formule : non vérifiée'}
async function api(path,opt={}){DIAG.apiRequests++;const token=opt.token||session?.access_token||KEY;const r=await fetch(SUPABASE_URL+path,{...opt,headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})}});const text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.error_description||data?.error||('Erreur '+r.status));return data}
function updateSessionUi(){const has=!!session?.access_token;$('logoutBtn').classList.toggle('hidden',!has);$('resumeBtn').classList.toggle('hidden',has||!saved())}
async function loadPlan(){if(!session?.user?.id)throw new Error('Session utilisateur absente');const d=await api('/rest/v1/subscriptions?select=plan,status&user_id=eq.'+encodeURIComponent(session.user.id)+'&livemode=eq.true&status=in.(active,trialing)&limit=1');currentPlan=C.plan(d?.[0]?.plan||'free');$('planLabel').textContent='Formule : '+C.rights(currentPlan).label;return currentPlan}
async function login(){const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<8){$('authStatus').textContent='Email valide et mot de passe de 8 caractères minimum.';return}setBusy('loginBtn',true);$('authStatus').textContent='Connexion…';try{const d=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password}),token:KEY});save(d);const user=await api('/auth/v1/user',{token:d.access_token});save({...d,user});await loadPlan();$('authStatus').textContent='Connecté. Aucun autre chargement automatique.'}catch(e){$('authStatus').textContent='Erreur : '+e.message}finally{setBusy('loginBtn',false)}}
async function signup(){const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<8){$('authStatus').textContent='Email valide et mot de passe de 8 caractères minimum.';return}setBusy('signupBtn',true);$('authStatus').textContent='Création du compte…';try{const d=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password}),token:KEY});if(d?.access_token){save(d);const user=await api('/auth/v1/user',{token:d.access_token});save({...d,user});await loadPlan();$('authStatus').textContent='Compte créé et connecté.'}else $('authStatus').textContent='Compte créé. Confirmez votre email puis connectez-vous.'}catch(e){$('authStatus').textContent='Erreur : '+e.message}finally{setBusy('signupBtn',false)}}
async function resume(){const s=saved();if(!s?.access_token)return;setBusy('resumeBtn',true);$('authStatus').textContent='Vérification de la session…';try{let user;try{user=await api('/auth/v1/user',{token:s.access_token});save({...s,user})}catch{if(!s.refresh_token)throw new Error('Session expirée');const fresh=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token}),token:KEY});user=await api('/auth/v1/user',{token:fresh.access_token});save({...fresh,user})}await loadPlan();$('authStatus').textContent='Session reprise.'}catch(e){clear();$('authStatus').textContent='Session non reprise : '+e.message}finally{setBusy('resumeBtn',false)}}
function logout(){clear();$('authStatus').textContent='Déconnecté.'}
function setBusy(id,v){const b=$(id);if(b)b.disabled=v}
async function search(){if(!session?.access_token){$('searchStatus').textContent='Connectez-vous d’abord.';return}const activity=$('activity').value.trim(),address=$('address').value.trim(),requested=Number($('radius').value||10);if(!activity||address.length<5){$('searchStatus').textContent='Renseignez activité et adresse.';return}setBusy('searchBtn',true);$('searchStatus').textContent='Recherche en cours…';try{DIAG.apiRequests++;const r=await fetch(SUPABASE_URL+'/functions/v1/local-prospects',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({activity,address,radius:requested})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('Erreur '+r.status));currentPlan=C.plan(d.plan);rows=C.capRows(currentPlan,d.prospects);renderRows(d.radius_km,d.limits?.details!==false);$('planLabel').textContent='Formule : '+C.rights(currentPlan).label;$('searchStatus').textContent='Recherche terminée : '+rows.length+' établissement(s).'}catch(e){rows=[];renderRows(null,false);$('searchStatus').textContent='Recherche impossible : '+e.message}finally{setBusy('searchBtn',false)}}
function demo(){currentPlan='essential';rows=SIM.map(x=>({...x,recommended_offers:C.recommendations('Imprimerie / signalétique',x.sector)}));renderRows(10,true);$('planLabel').textContent='Simulation : Essentiel — 9,90 €';$('searchStatus').textContent='Simulation locale uniquement : aucun appel API effectué.'}
function renderRows(radius,details){$('total').textContent=rows.length;$('prospects').textContent=rows.filter(x=>x.relation==='prospect').length;$('competitors').textContent=rows.filter(x=>x.relation==='competitor').length;$('radiusStat').textContent=radius?radius+' km':'—';$('feed').innerHTML=rows.length?rows.map(x=>{const comp=x.relation==='competitor';const offers=Array.isArray(x.recommended_offers)?x.recommended_offers:[];return '<article class="card"><div class="cardhead"><div><div class="company">'+esc(x.company||'Établissement')+'</div><div class="meta">'+esc(x.sector||'Entreprise locale')+(x.city?' · '+esc(x.city):'')+(x.distance_km!=null?' · '+esc(x.distance_km)+' km':'')+'</div></div><span class="pill '+(comp?'competitor':'prospect')+'">'+(comp?'CONCURRENT':'PROSPECT '+esc(x.score||'—')+'/100')+'</span></div><div class="why">'+esc(x.why||'Prospect à qualifier.')+'</div>'+(offers.length?'<div class="offers">'+offers.map(o=>'<span>'+esc(o)+'</span>').join('')+'</div>':'')+(details&&x.siret?'<div class="meta" style="margin-top:8px">SIRET '+esc(x.siret)+'</div>':'')+'</article>'}).join(''):'<div class="muted">Aucun résultat.</div>'}
async function openPipeline(){if(!session?.user?.id){$('pipeline').textContent='Connectez-vous d’abord.';return}if(!C.rights(currentPlan).pipeline){$('pipeline').textContent='Pipeline disponible à partir d’Essentiel.';return}setBusy('pipelineBtn',true);$('pipeline').textContent='Chargement du pipeline…';try{const d=await api('/rest/v1/local_prospect_pipeline?select=id,company,sector,status,score,distance_km&user_id=eq.'+encodeURIComponent(session.user.id)+'&order=created_at.desc');pipe=Array.isArray(d)?d:[];$('pipeline').innerHTML=pipe.length?pipe.map(x=>'<div style="padding:8px 0;border-top:1px solid #263957"><b>'+esc(x.company)+'</b><div class="meta">'+esc(x.sector||'')+' · '+esc(x.status||'')+'</div></div>').join(''):'Pipeline vide.'}catch(e){$('pipeline').textContent='Erreur pipeline : '+e.message}finally{setBusy('pipelineBtn',false)}}
async function checkPlan(){if(!session?.user?.id){$('paymentBanner').textContent='Connectez-vous puis cliquez de nouveau sur Vérifier mon abonnement.';return}setBusy('checkPlanBtn',true);try{await loadPlan();$('paymentBanner').classList.remove('err');$('paymentBanner').classList.add('ok');$('paymentBanner').textContent='Abonnement vérifié : '+C.rights(currentPlan).label+'.'}catch(e){$('paymentBanner').textContent='Vérification impossible : '+e.message}finally{setBusy('checkPlanBtn',false)}}
function buy(code){if(!session?.user?.id){$('authStatus').textContent='Connectez-vous avant de choisir un abonnement.';location.hash='';return}const u=CHECKOUT[code];if(!u)return;location.assign(u+'?client_reference_id='+encodeURIComponent(session.user.id)+'&prefilled_email='+encodeURIComponent(session.user.email||$('email').value.trim()))}
function selfTest(){const tests=[];const ok=(name,cond)=>tests.push({name,ok:!!cond});ok('Gratuit = 5',C.rights('free').max===5);ok('Essentiel = 50 / 10 km',C.rights('essential').max===50&&C.rights('essential').radius===10&&C.rights('essential').pipeline);ok('Pro = 250 / 25 km / CSV',C.rights('pro').max===250&&C.rights('pro').radius===25&&C.rights('pro').exportCsv);ok('Agence = 500 / 50 km',C.rights('agency').max===500&&C.rights('agency').radius===50);ok('Imprimeur concurrent détecté',C.relation('imprimerie','18.12Z','Imprimerie / production graphique')==='competitor');ok('Assurance = prospect imprimeur',C.relation('imprimerie','66.22Z','Assurance / courtage')==='prospect');ok('Pas de réseau automatique',C.startupPolicy().automaticNetwork===false&&DIAG.automaticNetwork===false);ok('Pas de service worker',C.startupPolicy().serviceWorker===false&&DIAG.serviceWorker===false);const passed=tests.filter(t=>t.ok).length;$('startupStatus').className='status '+(passed===tests.length?'ok':'err');$('startupStatus').innerHTML='<b>Autotest local : '+passed+'/'+tests.length+' réussis.</b><br>'+tests.map(t=>(t.ok?'✓ ':'✗ ')+esc(t.name)).join('<br>')}
function boot(){updateSessionUi();const q=new URLSearchParams(location.search);if(q.get('payment')==='success')$('paymentBanner').classList.remove('hidden');$('demoBtn').onclick=demo;$('selfTestBtn').onclick=selfTest;$('loginBtn').onclick=login;$('signupBtn').onclick=signup;$('resumeBtn').onclick=resume;$('logoutBtn').onclick=logout;$('searchBtn').onclick=search;$('pipelineBtn').onclick=openPipeline;$('checkPlanBtn').onclick=checkPlan;document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy));$('startupStatus').textContent='Démarrage : 0 appel API automatique effectué.'}
boot();
