(()=>{
if(typeof S==='undefined'||typeof sb==='undefined')return;
S.claims=S.claims||[];S.adminClaims=S.adminClaims||[];
const _loadPrivate=loadPrivate,_accountPage=accountPage,_proAccount=proAccount,_businessCard=businessCard,_viewBusiness=viewBusiness;
loadPrivate=async function(){await _loadPrivate();if(!S.session){S.claims=[];S.adminClaims=[];return}const uid=S.session.user.id;const c=await sb.from('ic_business_claims').select('*').eq('claimant_id',uid).order('created_at',{ascending:false});S.claims=c.data||[];if(S.profile?.role==='admin'){const a=await sb.from('ic_business_claims').select('*').eq('status','pending').order('created_at',{ascending:true});S.adminClaims=a.data||[]}else S.adminClaims=[]};
function claimable(b){return b&&b.source==='sirene_officiel'&&!b.is_claimed&&!b.owner_id}
businessCard=function(b){let h=_businessCard(b);if(claimable(b))h=h.replace('</article>',`<div class="actions" style="margin-top:8px"><button class="btn" onclick="openClaimBusiness('${b.id}')">🏪 C’est mon entreprise</button></div></article>`);return h};
viewBusiness=function(id){_viewBusiness(id);const b=S.businesses.find(x=>x.id===id);if(claimable(b)&&modalBody){modalBody.insertAdjacentHTML('beforeend',`<div class="notice" style="margin-top:14px"><b>Fiche officielle non revendiquée</b><p>Vous représentez cet établissement ? Demandez à récupérer cette fiche après vérification.</p><button class="btn primary" onclick="openClaimBusiness('${id}')">🏪 C’est mon entreprise — Revendiquer</button></div>`)} };
window.openClaimBusiness=function(id){const b=S.businesses.find(x=>x.id===id);if(!b)return;if(!S.session){say('Connectez-vous ou créez un compte professionnel pour revendiquer cette fiche.');authModal('businesses');return}if(!claimable(b))return say('Cette fiche est déjà revendiquée.');const pending=S.claims.find(c=>c.business_id===id&&c.status==='pending');if(pending)return openModal(`<h2>Demande déjà envoyée</h2><p>Votre demande pour <b>${esc(b.name)}</b> est en cours de vérification.</p><div class="notice">Statut : <b>⏳ En attente</b></div><button class="btn brand" onclick="closeModal();go('account')">Voir mon espace professionnel</button>`);openModal(`<h2>🏪 Revendiquer ${esc(b.name)}</h2><p class="muted">La fiche ne sera transférée qu’après vérification.</p><div class="notice"><b>${esc(b.name)}</b><br>${esc(b.address||'')}${b.siret?`<br>SIRET : ${esc(b.siret)}`:''}</div><div class="form"><label>Nom et prénom</label><input id="claimName" value="${esc(S.profile?.display_name||'')}"><label>Votre fonction</label><input id="claimRole" placeholder="Gérant, dirigeant, responsable…"><label>Email de contact</label><input id="claimEmail" type="email" value="${esc(S.session.user.email||'')}"><label>Téléphone</label><input id="claimPhone" type="tel"><label>Justificatif / explication</label><textarea id="claimProof" rows="4" placeholder="Expliquez votre lien avec l’entreprise"></textarea><label>Lien justificatif (facultatif)</label><input id="claimUrl" type="url" placeholder="https://site-officiel.fr"><button class="btn primary" onclick="submitBusinessClaim('${id}')">Envoyer ma demande</button></div>`)};
window.submitBusinessClaim=async function(id){const args={p_business_id:id,p_full_name:$('#claimName').value.trim(),p_role_in_business:$('#claimRole').value.trim(),p_contact_email:$('#claimEmail').value.trim(),p_contact_phone:$('#claimPhone').value.trim()||null,p_proof_note:$('#claimProof').value.trim()||null,p_proof_url:$('#claimUrl').value.trim()||null};if(!args.p_full_name||!args.p_role_in_business||!args.p_contact_email)return say('Nom, fonction et email sont obligatoires.');const {error}=await sb.rpc('ic_submit_business_claim',args);if(error)return say(error.message);closeModal();say('Demande envoyée. Elle doit être validée avant le transfert de la fiche.');await loadPrivate();go('account')};
function st(v){return v==='approved'?'✅ Validée':v==='rejected'?'❌ Refusée':'⏳ En attente'}
function claimsHtml(){return S.claims.length?`<div class="cards">${S.claims.map(c=>{const b=S.businesses.find(x=>x.id===c.business_id);return `<div class="card"><span class="pill">${st(c.status)}</span><h3>${esc(b?.name||'Entreprise')}</h3><div class="muted">Demande du ${new Date(c.created_at).toLocaleDateString('fr-FR')}</div>${c.admin_note?`<p>${esc(c.admin_note)}</p>`:''}</div>`}).join('')}</div>`:'<div class="empty">Aucune demande de revendication.</div>'}
proAccount=function(){_proAccount();if(!S.myBusinesses.length){main.insertAdjacentHTML('afterbegin',`<div class="sectionhead"><div><h2>Retrouver mon entreprise</h2><p>Avant de créer une fiche, recherchez votre établissement dans l’annuaire officiel.</p></div><button class="btn brand" onclick="go('businesses')">🔎 Rechercher ma fiche</button></div>${S.claims.length?`<div class="sectionhead"><div><h2>Mes demandes de revendication</h2></div></div>${claimsHtml()}`:''}`)}};
accountPage=function(){if(S.session&&S.profile?.role==='admin')return adminAccount();return _accountPage()};
window.adminAccount=function(){main.innerHTML=`<div class="sectionhead"><div><h2>Administration Issoire Connect</h2><p>Validation des revendications d’entreprises.</p></div><button class="btn" onclick="logout()">Déconnexion</button></div><div class="kpis"><div class="kpi"><span class="muted">En attente</span><strong>${S.adminClaims.length}</strong></div><div class="kpi"><span class="muted">Professionnels</span><strong>${S.stats.pros}</strong></div></div><div class="sectionhead"><div><h2>Demandes à vérifier</h2></div></div>${S.adminClaims.length?S.adminClaims.map(adminClaimCard).join(''):'<div class="empty">Aucune demande en attente.</div>'}`};
window.adminClaimCard=function(c){const b=S.businesses.find(x=>x.id===c.business_id);return `<div class="card" style="margin-bottom:10px"><span class="pill">⏳ À vérifier</span><h3>${esc(b?.name||'Entreprise')}</h3><div class="muted">${esc(b?.address||'')}${b?.siret?` · SIRET ${esc(b.siret)}`:''}</div><p><b>Demandeur :</b> ${esc(c.full_name)} — ${esc(c.role_in_business)}<br><b>Email :</b> ${esc(c.contact_email)}${c.contact_phone?`<br><b>Tél. :</b> ${esc(c.contact_phone)}`:''}</p>${c.proof_note?`<div class="notice"><b>Justification :</b><br>${esc(c.proof_note)}</div>`:''}${c.proof_url?`<p><a class="btn" href="${esc(c.proof_url)}" target="_blank" rel="noopener">Ouvrir le justificatif</a></p>`:''}<div class="actions"><button class="btn green" onclick="reviewClaim('${c.id}','approved')">✅ Valider</button><button class="btn" onclick="reviewClaim('${c.id}','rejected')">❌ Refuser</button></div></div>`};
window.reviewClaim=function(id,status){openModal(`<h2>${status==='approved'?'Valider la revendication':'Refuser la revendication'}</h2><p>${status==='approved'?'La fiche sera transférée au compte du demandeur.':'La fiche restera non revendiquée.'}</p><div class="form"><label>Note administrative (facultatif)</label><textarea id="reviewNote" rows="4"></textarea><button class="btn ${status==='approved'?'green':'primary'}" onclick="confirmReviewClaim('${id}','${status}')">Confirmer</button></div>`)};
window.confirmReviewClaim=async function(id,status){const {error}=await sb.rpc('ic_review_business_claim',{p_claim_id:id,p_status:status,p_admin_note:$('#reviewNote').value.trim()||null});if(error)return say(error.message);closeModal();say(status==='approved'?'Fiche transférée au professionnel.':'Demande refusée.');await refresh()};
})();
