(()=>{
'use strict';
if(typeof window==='undefined'||typeof S==='undefined')return;
const V='52.0';
const e52=v=>typeof esc==='function'?esc(String(v??'')):String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function adMarkup(a,{preview=false}={}){const b=a.business||{};return `<div class="row between"><div><span class="pill">${preview?'👁 APERÇU HABITANT · ':''}${a.placement==='premium'?'⭐ SPONSORISÉ PREMIUM':'📢 SPONSORISÉ'}</span><div class="muted" style="margin-top:5px">Publicité locale ciblée · ${Number(a.target_radius_km||0)} km</div></div></div><h3 style="margin:11px 0 3px">${e52(a.title||'Offre locale')}</h3><div><b>${e52(b.name||'Professionnel local')}</b>${b.city?` <span class="muted">· ${e52(b.city)}</span>`:''}</div>`}
const DEMO_AD={id:'demo-ad',business_id:'demo-pro',title:'Diagnostic énergie offert pour toute demande de devis',target_radius_km:20,target_audience:'residents',placement:'premium',business:{id:'demo-pro',name:'Atelier Local Démo',city:'Issoire',category:'Rénovation'}};
function demoHeader(kind){return `<div data-ic-demo-screen="${kind}" class="demohero" style="position:relative"><span class="pill" style="background:#fff;color:#123d73">🎬 MODE DÉMO · DONNÉES FICTIVES</span><h2 style="margin-top:10px">${kind==='resident'?'👤 Profil Habitant — Camille Démo':'🚀 Profil Pro 360 — Atelier Local Démo'}</h2><p style="margin:4px 0 0;opacity:.92">Issoire · démonstration commerciale sans compte réel ni écriture en base.</p></div>`}
function demoNav(){return `<div class="actions" style="margin:0 0 12px"><button class="btn" onclick="openDemoHub()">🎬 Menu Démo</button><button class="btn" onclick="openIc52AdStory()">🔄 Scénario Pub Pro → Habitant</button></div>`}
window.openIc52ResidentDemo=function(){
 openModal(`${demoHeader('resident')}${demoNav()}<div class="kpis"><div class="kpi"><small class="muted">Rayon</small><strong>10 km</strong></div><div class="kpi"><small class="muted">Favoris</small><strong>6</strong></div><div class="kpi"><small class="muted">Avantages</small><strong>12</strong></div><div class="kpi"><small class="muted">Agenda</small><strong>2</strong></div></div><h3>🏠 Mon accueil local</h3><div class="gridmenu"><button class="tile" onclick="openIc52DemoRadar()"><span>📡</span><b>Radar</b></button><button class="tile" onclick="openIc52DemoNeeds()"><span>📣</span><b>Mon besoin</b></button><button class="tile" onclick="openIc52DemoDeals()"><span>🎁</span><b>Avantages</b></button><button class="tile" onclick="openIc52DemoAgenda()"><span>🗓️</span><b>Agenda</b></button></div><h3 style="margin-top:16px">📢 Publicité locale visible par l’habitant</h3><article class="card" style="border:1px solid #ffd2a6;background:linear-gradient(135deg,#fff7ec,#fff)">${adMarkup(DEMO_AD,{preview:true})}</article><h3 style="margin-top:16px">🔥 Près de chez moi</h3><div class="cards"><article class="card"><span class="pill">🎁 AVANTAGE IC</span><h3>-10 % sur un contrôle vélo</h3><div class="muted">Cycle Démo · 1,2 km</div></article><article class="card"><span class="pill">💼 EMPLOI</span><h3>Employé polyvalent</h3><div class="muted">Commerce Démo · Issoire</div></article><article class="card"><span class="pill">📅 ÉVÉNEMENT</span><h3>Marché des créateurs</h3><div class="muted">Samedi · centre-ville</div></article></div>`);
};
window.openIc52ProDemo=function(){
 openModal(`${demoHeader('pro')}${demoNav()}<div class="notice"><b>Pro 360 — 19,99 €/mois</b><br>4,99 € pour être trouvé. 19,99 € pour trouver des clients.</div><div class="kpis" style="margin-top:12px"><div class="kpi"><small class="muted">Prospects</small><strong>18</strong></div><div class="kpi"><small class="muted">Besoins confirmés</small><strong>4</strong></div><div class="kpi"><small class="muted">Campagnes</small><strong>1</strong></div><div class="kpi"><small class="muted">Avis</small><strong>4,8★</strong></div></div><h3>Tableau de bord Pro</h3><div class="demolist"><button class="democard" onclick="openIc52DemoProspects()"><div class="big">🎯</div><h3>Radar Prospects</h3><p>Détecter les besoins locaux compatibles.</p></button><button class="democard" onclick="openIc52DemoPipeline()"><div class="big">📌</div><h3>Suivi commercial</h3><p>Prospects, relances et statuts.</p></button><button class="democard" onclick="openIc52DemoCampaign()"><div class="big">📣</div><h3>Mes campagnes</h3><p>Créer une publicité ciblée Habitants.</p></button><button class="democard" onclick="openIc52DemoServices()"><div class="big">🛍️</div><h3>Produits & services</h3><p>Prestations, tarifs et devis.</p></button></div><h3 style="margin-top:16px">📣 Campagne Démo active</h3><article class="card" style="border-left:4px solid #f47721"><span class="pill">⭐ PREMIUM · HABITANTS · 20 KM</span><h3>${e52(DEMO_AD.title)}</h3><p class="muted">Cette campagne est ensuite visible dans le parcours Habitant.</p><div class="row" style="gap:18px"><b>1 248 impressions</b><b>63 clics</b><b>CTR 5,05 %</b></div><div class="actions"><button class="btn brand" onclick="openIc52ResidentDemo()">👁 Voir le résultat côté Habitant</button></div></article>`);
};
window.openIc52AdStory=function(){
 openModal(`<div class="demohero"><span class="pill" style="background:#fff;color:#123d73">🎬 DÉMO COMMERCIALE</span><h2 style="margin-top:10px">🔄 Du Pro jusqu’à l’Habitant</h2><p style="margin:0;opacity:.92">La démonstration montre exactement où va une publicité créée par un professionnel.</p></div><div class="demoflow"><div class="demostep"><b>1</b><div><strong>Le Pro crée sa campagne</strong><br><span class="muted">Audience : Habitants · rayon : 20 km · placement Premium.</span></div></div><div class="demostep"><b>2</b><div><strong>Issoire Connect cible localement</strong><br><span class="muted">La campagne respecte le rayon, les dates et la fréquence.</span></div></div><div class="demostep"><b>3</b><div><strong>L’Habitant voit “SPONSORISÉ”</strong><br><span class="muted">Accueil, recherche, bons plans, annuaire, annonces et compte habitant peuvent recevoir une insertion.</span></div></div><div class="demostep"><b>4</b><div><strong>Le clic est mesuré</strong><br><span class="muted">Impressions, clics et CTR remontent au professionnel.</span></div></div></div><article class="card" style="border:1px solid #ffd2a6;background:#fffaf3">${adMarkup(DEMO_AD,{preview:true})}</article><div class="actions"><button class="btn brand" onclick="openIc52ProDemo()">🚀 Voir le profil Pro</button><button class="btn" onclick="openIc52ResidentDemo()">👤 Voir le profil Habitant</button></div>`);
};
window.openIc52DemoRadar=()=>openModal(`${demoHeader('resident')}${demoNav()}<h2>📡 Radar</h2><div class="card"><b>Plombier Démo</b><div class="muted">1,8 km · 4,9★ · répond généralement en moins d’1 h</div><div class="actions"><button class="btn brand">Voir la fiche</button><button class="btn">❤️ Favori</button></div></div>`);
window.openIc52DemoNeeds=()=>openModal(`${demoHeader('resident')}${demoNav()}<h2>📣 Mon besoin</h2><div class="notice">Exemple : « Je cherche quelqu’un pour refaire ma salle de bain. »</div><div class="demoresult"><b>Publié gratuitement.</b><br>Les Pros 360 compatibles pourront le voir comme 🔥 Besoin confirmé, sans exposer vos données privées.</div>`);
window.openIc52DemoDeals=()=>openModal(`${demoHeader('resident')}${demoNav()}<h2>🎁 Avantages IC</h2><div class="cards"><article class="card"><b>Café offert</b><div class="muted">Restaurant Démo</div></article><article class="card"><b>-5 €</b><div class="muted">Coiffeur Démo</div></article></div>`);
window.openIc52DemoAgenda=()=>openModal(`${demoHeader('resident')}${demoNav()}<h2>🗓️ Mon agenda privé</h2><div class="card"><b>Demain · 14:30</b><p>Rendez-vous devis rénovation</p><span class="pill">Rappel 1 h avant</span></div>`);
window.openIc52DemoProspects=()=>openModal(`${demoHeader('pro')}${demoNav()}<h2>🎯 Radar Prospects</h2><article class="card" style="border-left:4px solid #f47721"><span class="pill">🔥 BESOIN CONFIRMÉ · 94 %</span><h3>Rénovation salle de bain</h3><div class="muted">Issoire · 2,4 km</div><div class="actions"><button class="btn brand">Ajouter aux prospects</button><button class="btn">Contacter</button></div></article><article class="card"><span class="pill">🔵 CIBLE COMPATIBLE · 82 %</span><h3>Projet rénovation locale</h3><div class="muted">Pas de besoin confirmé</div></article>`);
window.openIc52DemoPipeline=()=>openModal(`${demoHeader('pro')}${demoNav()}<h2>📌 Suivi commercial</h2><div class="cards"><article class="card"><span class="pill">NOUVEAU</span><h3>Salle de bain</h3></article><article class="card"><span class="pill">CONTACTÉ</span><h3>Isolation combles</h3></article><article class="card"><span class="pill">DEVIS</span><h3>Peinture façade</h3></article></div>`);
window.openIc52DemoCampaign=()=>openModal(`${demoHeader('pro')}${demoNav()}<h2>📣 Créer une campagne</h2><div class="form"><label>Titre</label><input value="${e52(DEMO_AD.title)}" disabled><label>Audience</label><input value="Habitants" disabled><label>Rayon</label><input value="20 km" disabled><label>Placement</label><input value="Premium" disabled></div><div class="actions"><button class="btn brand" onclick="openIc52ResidentDemo()">▶ Simuler la publication et voir côté Habitant</button></div>`);
window.openIc52DemoServices=()=>openModal(`${demoHeader('pro')}${demoNav()}<h2>🛍️ Mes prestations</h2><div class="cards"><article class="card"><h3>Diagnostic rénovation</h3><div class="price">Sur devis</div><span class="pill">Chez le client</span></article><article class="card"><h3>Étude énergétique</h3><div class="price">89,00 €</div><span class="pill">Particuliers + Pros</span></article></div>`);
window.copyIc52DemoLink=async function(kind){const u=new URL(location.href);u.searchParams.set('demo',kind);try{await navigator.clipboard.writeText(u.href);say('Lien Démo copié.')}catch{openModal(`<h2>Lien Démo</h2><input value="${e52(u.href)}" style="width:100%;padding:10px">`)}};
window.openDemoHub=function(){openModal(`<div class="demohero"><span class="pill" style="background:#fff;color:#123d73">🎬 PRÉSENTATION SANS COMPTE</span><h2 style="margin-top:10px">Issoire Connect — Mode Démo</h2><p style="margin:0;opacity:.92">Choisissez le public à qui vous présentez l’application. Toutes les données affichées ci-dessous sont fictives.</p></div><div class="demolist"><button class="democard" onclick="openIc52ResidentDemo()"><div class="big">👤</div><h3>Démo Habitant</h3><p>Radar, besoins, avantages, annonces, agenda et publicité locale.</p><span class="pill">Présenter à un particulier</span></button><button class="democard" onclick="openIc52ProDemo()"><div class="big">🚀</div><h3>Démo Pro 360</h3><p>Radar Prospects, CRM, prestations, avantages et campagnes sponsorisées.</p><span class="pill">Présenter à un professionnel</span></button></div><button class="democard" style="width:100%;margin-top:10px" onclick="openIc52AdStory()"><div class="big">🔄</div><h3>Scénario Pub : Pro → Habitant</h3><p>Montrez où apparaît concrètement une campagne professionnelle.</p></button><div class="actions"><button class="btn" onclick="copyIc52DemoLink('resident')">🔗 Copier lien Démo Habitant</button><button class="btn" onclick="copyIc52DemoLink('pro')">🔗 Copier lien Démo Pro</button><button class="btn" onclick="copyIc52DemoLink('ads')">🔗 Copier lien Démo Pub</button></div>`)};
async function launchQueryDemo(){const kind=new URLSearchParams(location.search).get('demo');if(!kind)return;for(let i=0;i<20;i++){if(typeof openModal==='function'){if(kind==='resident')openIc52ResidentDemo();else if(kind==='pro')openIc52ProDemo();else if(kind==='ads')openIc52AdStory();else openDemoHub();return}await wait(150)}}
setTimeout(launchQueryDemo,800);
window.icV52Demo={version:V,openResident:window.openIc52ResidentDemo,openPro:window.openIc52ProDemo,openAds:window.openIc52AdStory};
})();