(()=>{
if(typeof S==='undefined'||typeof sb==='undefined')return;
const E=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const _proAccountEnt=proAccount;
const mine=()=>Array.isArray(S.myBusinesses)?S.myBusinesses:[];
S.businessEntitlements=S.businessEntitlements||{};
const LABELS={free:'Gratuit',essential:'Essentiel',pro:'Pro',proplus:'Pro+'};
const limitText=v=>v===null||v===undefined?'Illimité':String(v);
function planLabel(p){return LABELS[p]||p||'Gratuit'}
function summary(e){if(!e)return 'Chargement du forfait…';return `${planLabel(e.plan)} · rayon ${e.current_radius_km}/${e.max_radius_km} km · ${e.active_products}/${limitText(e.active_product_limit)} produits · ${e.active_classifieds}/${e.active_classified_limit} annonces Pro`}
async function loadEntitlements(id){
 if(!S.session)return null;
 try{const {data,error}=await sb.rpc('ic_business_entitlements',{p_business_id:id});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)return null;S.businessEntitlements[id]=row;document.querySelectorAll(`[data-ic-entitlement-summary="${CSS.escape(String(id))}"]`).forEach(x=>x.textContent=summary(row));document.querySelectorAll(`[data-ic-plan-label="${CSS.escape(String(id))}"]`).forEach(x=>x.textContent=planLabel(row.plan));return row}catch(e){console.warn('Issoire Connect entitlements',e);return null}
}
window.refreshBusinessEntitlements=loadEntitlements;
window.openBusinessRadius=async function(id){
 const b=mine().find(x=>x.id===id);if(!b)return say('Établissement introuvable.');const e=await loadEntitlements(id);if(!e)return say('Impossible de charger votre forfait.');
 openModal(`<h2>📍 Rayon de visibilité</h2><p><b>${E(b.name)}</b> · forfait ${E(planLabel(e.plan))}</p><div class="notice">Votre fiche peut être mise en avant jusqu’à <b>${Number(e.max_radius_km)} km</b> selon votre forfait.</div><div class="form"><label>Rayon en kilomètres</label><input id="entRadius" type="number" min="1" max="${Number(e.max_radius_km)}" value="${Number(e.current_radius_km)}"><button class="btn brand" onclick="saveBusinessRadius('${E(id)}')">💾 Enregistrer le rayon</button></div>`)
};
window.saveBusinessRadius=async function(id){const b=mine().find(x=>x.id===id);if(!b)return say('Établissement introuvable.');const radius=Number($('#entRadius')?.value||0);const {data,error}=await sb.rpc('ic_set_business_visibility_radius',{p_business_id:id,p_radius:radius});if(error)return say(String(error.message||error).replaceAll('_',' '));b.visibility_radius_km=Number(data||radius);closeModal();say(`Rayon réglé à ${Number(data||radius)} km.`);await loadEntitlements(id);proAccount()};
function benefits(e){if(!e)return '<div class="muted">Chargement des droits…</div>';const productLimit=limitText(e.active_product_limit);return `<div class="grid" style="margin-top:10px"><div class="notice"><b>📍 Visibilité</b><br>${Number(e.current_radius_km)} km / ${Number(e.max_radius_km)} km</div><div class="notice"><b>🛍 Produits/services</b><br>${Number(e.active_products)} / ${E(productLimit)}</div><div class="notice"><b>📌 Annonces Pro</b><br>${Number(e.active_classifieds)} / ${Number(e.active_classified_limit)}</div><div class="notice"><b>🔔 Alertes abonnés</b><br>${Number(e.daily_alert_limit)} maximum / 24 h</div><div class="notice"><b>💳 Réservations</b><br>${e.reservations_allowed?'Incluses':'Non incluses'}${e.reservations_allowed?` · ${e.reservations_enabled?'activées':'désactivées'}`:''}</div><div class="notice"><b>📣 Campagnes sponsorisées</b><br>${e.sponsored_ads_allowed?'Incluses':'Pro+ uniquement'}</div></div>`}
function card(b){const e=S.businessEntitlements[b.id];return `<article class="card" style="margin-bottom:12px"><div class="row between"><div><h3>${E(b.name)}</h3><span class="pill" data-ic-plan-label="${E(b.id)}">${E(planLabel(e?.plan||b.plan))}</span></div><button class="btn" onclick="refreshBusinessEntitlements('${E(b.id)}')">↻ Actualiser</button></div><div class="muted" data-ic-entitlement-summary="${E(b.id)}">${E(summary(e))}</div>${benefits(e)}<div class="actions" style="margin-top:10px"><button class="btn brand" onclick="openBusinessRadius('${E(b.id)}')">📍 Régler mon rayon</button>${e?.reservations_allowed?`<button class="btn" onclick="setBusinessReservations('${E(b.id)}',${!e.reservations_enabled})">${e.reservations_enabled?'Désactiver':'Activer'} les réservations</button>`:''}</div></article>`}
function section(){if(!mine().length)return '';return `<div class="sectionhead"><div><h2>🎯 Mon forfait & mes droits</h2><p>Les limites affichées viennent directement de votre abonnement actif. Un impayé met les fonctions premium en pause sans supprimer vos contenus.</p></div></div>${mine().map(card).join('')}`}
proAccount=function(){const out=_proAccountEnt();if(S.session&&mine().length){try{main.insertAdjacentHTML('beforeend',section());setTimeout(()=>mine().forEach(b=>loadEntitlements(b.id).then(()=>{if(document.body.contains(main))proAccount()})),0)}catch(e){console.error('Issoire Connect entitlements panel',e)}}return out};
})();
