'use strict';
const CACHE='issoire-connect-v64-mobile-20260906';
const CORE=['./?v=64.0','index.html?v=64.0','installer.html?v=64.0','manifest.webmanifest?v=64.0','icon.svg','icon-192.svg','icon-512.svg','v58-stability-cloud.js?v=64.0-20260906','v59-admin-security.js?v=64.0-20260906','v59-version-fix.js?v=64.0-20260906','v59-push-register.js?v=64.0-20260906','v60-checkout-rc.js?v=64.0-20260906','v60-version-fix.js?v=64.0-20260906','v61-security-admin.js?v=64.0-20260906','v62-legal-privacy.js?v=64.0-20260906','v62-release-gate.js?v=64.0-20260906','v62-version-fix.js?v=64.0-20260906','v63c-00.txt?v=64.0-20260906','v63c-01.txt?v=64.0-20260906','v63c-02.txt?v=64.0-20260906','v63f-00.txt?v=64.0-20260906','v64-mobile-install.js?v=64.0-20260906',...Array.from({length:10},(_,i)=>`v57-${String(i).padStart(2,'0')}.txt?v=64.0-20260906`)];
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE);await Promise.all(CORE.map(async u=>{try{const r=await fetch(u,{cache:'no-store'});if(r.ok)await c.put(u,r.clone())}catch{}}));await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('issoire-connect-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener('message',e=>{if(e.data==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==self.location.origin)return;const network=async()=>{const r=await fetch(e.request,{cache:'no-store'});if(r.ok){const c=await caches.open(CACHE);c.put(e.request,r.clone()).catch(()=>{})}return r};if(e.request.mode==='navigate'){e.respondWith(network().catch(async()=>await caches.match('./?v=64.0')||await caches.match('index.html?v=64.0')||Response.error()));return}if(/\/v57-\d\d\.txt$/.test(u.pathname)||/\/v63[cf]-\d\d\.txt$/.test(u.pathname)||/\/v(58|59|60|61|62|64)-.*\.js$/.test(u.pathname)||u.pathname.endsWith('/manifest.webmanifest')||u.pathname.endsWith('/icon.svg')||u.pathname.endsWith('/icon-192.svg')||u.pathname.endsWith('/icon-512.svg')||u.pathname.endsWith('/installer.html')||u.pathname.endsWith('/index.html')){e.respondWith(network().catch(()=>caches.match(e.request)));}});
self.addEventListener('push',e=>{let d={};try{d=e.data?e.data.json():{}}catch{try{d={body:e.data?.text()||''}}catch{d={}}}const title=d.title||'Issoire Connect';let target='./?v=64.0';try{const u=new URL(d.url||'./?v=64.0',self.location.origin);if(u.origin===self.location.origin)target=u.href}catch{}const options={body:d.body||'',icon:'icon.svg',badge:'icon.svg',tag:d.tag||'issoire-connect',data:{url:target},renotify:false};e.waitUntil(self.registration.showNotification(title,options))});
self.addEventListener('notificationclick',e=>{e.notification.close();const target=e.notification?.data?.url||new URL('./?v=64.0',self.location.href).href;e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const c of list){try{if(new URL(c.url).origin===self.location.origin){c.navigate(target);return c.focus()}}catch{}}return clients.openWindow(target)}))});
